<?php
/* @var array $objectData */
/* @var array $crumbs */
/* @var array $allData this is the recommended tutorials */

?>


<section class="section pt-0 section-padding">
    <div id="loadout-container" class="container pl-4 pt-6 pr-0 has-background-white pb-6">

        <div class="content is-flex flex-direction-column-mobile">
            <div id="loadout-content" class="is-flex is-flex-direction-column">
                <div class="is-flex is-flex-direction-column loadout-headers">
                    <nav class="breadcrumb" aria-label="breadcrumbs">
                        <ul class="breadcrumb-list">
                            <?php $counter = 0 ?>
                            <?php foreach ( $crumbs as $crumb ): ?>
                                <?php if( ( $counter + 1 ) == count($crumbs) ): ?>
                                    <li class="is-active"><a href="#" aria-current="page"><?=$crumb['word']?></a></li>
                                <?php else: ?>
                                    <li><a href="<?=$crumb['url']?>"><?=$crumb['word']?></a></li>
                                <?php endif; $counter++ ?>
                            <?php endforeach; ?>
                        </ul>
                    </nav>
                    <h1 class="title is-size-1 is-size-3-mobile has-text-main-color mt-0"><?=$objectData['title']?></h1>
                    <span class="is-size-5 is-size-6-mobile mb-3 has-text-grey-darker">Publicado el <?php echo strftime( "%d de %B, %Y" , $objectData['creationDate'])?></span>
                </div>
                <?php if( is_null($objectData['image_title']) !== true && $objectData['image_title'] != "" ): ?>
                    <figure class="mr-auto ml-auto loadout-image">
                        <img src="/uploads/images/tutorial/<?=$objectData['categoryName']?>/<?=$objectData['image_title']?>" class="" alt="">
                    </figure>
                <?php endif;?>

                <div class="is-flex is-flex-direction-column loadout-headers">
                    <?php $counter = 0; ?>
                    <?php foreach ( $objectData['description'][0]  as $descPart): ?>
                        <?php if( $counter == 3  ) : ?>
                            <?php if( is_null($objectData['image_footer'] !== true && $objectData['image_footer'] != "")): ?>
                                <figure class="mr-auto ml-auto loadout-image">
                                    <img src="/uploads/images/tutorial/<?=$objectData['categoryName']?>/<?=$objectData['image_footer']?>" class="" alt="">
                                </figure>
                            <?php endif;?>
                        <?php endif; ?>
                        <p class="is-size-4 is-text has-text-justified"><?=$descPart?></p>
                        <?php if( $counter == 1  ) : ?>
                            <?php if( is_null($objectData['image_desc']) !== true && $objectData['image_desc'] != "" ): ?>
                                <figure class="mr-auto ml-auto loadout-image">
                                    <img src="/uploads/images/tutorial/<?=$objectData['categoryName']?>/<?=$objectData['image_desc']?>" class="" alt="">
                                </figure>
                            <?php endif;?>
                        <?php endif; ?>
                        <?php $counter+=1; ?>
                    <?php endforeach; ?>
                </div>
            </div>
            <div id="other-loadouts">
                <div class="has-background-extra-info is-flex is-flex-direction-column p-3 mt-3">
                    <h3 class="title mt-1"><span class="is-text mr-5 is-size-4">Te puede interesar...</span><i class="fa-solid fa-angle-right"></i></h3>
                    <?php foreach ( $allData as $tutorial ): ?>
                        <div class="is-flex is-flex-direction-column">
                            <a href="/tutoriales/<?=$tutorial['lowerCatName']?>/<?=$tutorial['tutorial_id']?>/<?=$tutorial['uriTitle']?>" class="is-flex mb-2">
                                <figure class="image m-0 other-loadouts-img">
                                    <img class="object-fit" src="/uploads/images/tutorial/<?=$tutorial['categoryName']?>/<?=$tutorial['titleImage']?>" alt="" >
                                </figure>
                                <h4 class="is-inline-block title is-size-6 ml-2 is-align-self-center has-text-weight-light"><?=$tutorial['title']?></h4>
                            </a>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</section>