<?php
/* @var $allData */
/* @var $randomLoadouts */
/* @var $loadouts */
/* @var $lastNews */
/* @var $someNews */
/* @var $lastTutorial */
/* @var $someTutorials */

?>

        <!---------- HOME PAGE -------->
        <div id="home" class="container p-5 main-background-color">
            <div id="latest-posts" class="columns is-flex-direction-row p-3 mb-2 rounded-corners">
                <?php foreach ($randomLoadouts as $loadout): ?>

                    <div class="column is-relative is-flex custom-column is-flex-direction-column">
                        <a class="custom-column__img-link" href="/clases/<?=$loadout['gameUri']?>/<?=$loadout['loadout_id']?>/<?=$loadout['loadoutUri']?>">
                            <figure class="image is-100-height">
                                <img class="object-fit" src="/uploads/images/weapon/<?=$loadout['gameName']?>/<?=$loadout['weaponImage']?>">
                            </figure>
                        </a>
                        <div class="bottom-banner p-3 is-flex justify-self-start is-flex-direction-column is-align-items-self-start">
                            <a href="/clases/<?=$loadout['gameUri']?>" id="post-category" class="category custom-category ml-2 mt-1" ><?=$loadout['shortName']?></a>
                            <a href="/clases/<?=$loadout['gameUri']?>/<?=$loadout['loadout_id']?>/<?=$loadout['loadoutUri']?>">
                                <div id="title" class="post-title custom-title mt-2 ml-2 mr-2">
                                    <h2 class="title custom-title-h2"><?=$loadout['title']?></h2>
                                </div>
                                <div class="post-upload-info is-flex is-justify-content-start ml-2 mr-2 mt-2 is-flex-direction-column-widescreen">
                                    <span class="has-text-white custom-span"><i class="fa-solid fa-clock"></i> <?=strftime( "%d de %B de %Y" , $loadout['creationDate'])?></span>
                                    <span class="ml-2 has-text-white custom-span"><i class="fa-solid fa-circle i-font-size"></i> SudoKiss</span>
                                </div>
                            </a>
                        </div>
                    </div>
                <?php endforeach; ?>

            </div>

            <!---- CONTENT - NEWS, POSTS, TUTORIALS ----->
            <div id="content" class="is-fullwidth is-block rounded-corners overflow-hidden has-background-white">
                <div id="news" class="news is-inline-block has-background-white p-3">
                    <h2 class="title">Noticias</h2>
                    <div class="column is-relative is-flex custom-column is-flex-direction-column">
                        <a class="custom-column__img-link" href="/noticias/<?=$lastNews['lowerCatName']?>/<?=$lastNews['news_id']?>/<?=$lastNews['uriTitle']?>">
                            <figure class="image is-100-height">
                                <img class="object-fit" src="/uploads/images/news/<?=$lastNews['categoryName']?>/<?=$lastNews['titleImage']?>">
                            </figure>
                        </a>
                        <div class="bottom-banner p-3 is-flex justify-self-start is-flex-direction-column is-align-items-self-start">
                            <a href="/noticias/<?=$lastNews['lowerCatName']?>" id="post-category" class="category custom-category ml-2 mt-1" ><?=$lastNews['categoryName']?></a>
                            <a href="/noticias/<?=$lastNews['lowerCatName']?>/<?=$lastNews['news_id']?>/<?=$lastNews['uriTitle']?>">
                                <div id="title" class="post-title custom-title mt-2 ml-2 mr-2">
                                    <h2 class="title custom-title-h2"><?=$lastNews['title']?></h2>
                                </div>
                                <div class="post-upload-info is-flex is-justify-content-start ml-2 mr-2 mt-2 is-flex-direction-column-widescreen">
                                    <span class="has-text-white custom-span"><i class="fa-solid fa-clock"></i> <?=strftime( "%d de %B de %Y" , $lastNews['creationDate'])?></span>
                                    <span class="ml-2 has-text-white custom-span"><i class="fa-solid fa-circle i-font-size"></i> SudoKiss</span>
                                </div>
                            </a>
                        </div>
                    </div>
                    <ul class="home-list">
                        <?php foreach ( $someNews as $news ): ?>
                            <li><a href="/noticias/<?=$news['lowerCatName']?>/<?=$news['news_id']?>/<?=$news['uriTitle']?>"><?=$news['title']?></a></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <div id="posts" class="new-posts has-background-white is-inline-block p-3">
                    <div id="l-posts-container" class="is-flex is-flex-direction-column is-justify-content-center">
                        <?php foreach ( $loadouts as $loadout ): ?>
                            <article class="article post-id is-flex is-flex-direction-column has-background-white p-2 mb-3 mt-3" id="<?=$loadout['loadout_id']?>">
                                <div id="post-image" class="is-flex is-relative">
                                    <a href="/clases/<?=$loadout['gameUri']?>/<?=$loadout['loadout_id']?>/<?=$loadout['loadoutUri']?>">
                                        <figure class="image pt-2 pl-2 pr-2">
                                            <img src="/uploads/images/loadout/<?=$loadout['gameName']?>/<?=$loadout['image']?>" height="" width="" alt="<?=$loadout['title']?>">
                                        </figure>
                                    </a>
                                    <a href="/clases/<?=$loadout['gameUri']?>" class="category right" ><?=$loadout['shortName']?></a>
                                </div>
                                <a href="/clases/<?=$loadout['gameUri']?>/<?=$loadout['loadout_id']?>/<?=$loadout['loadoutUri']?>" class="pl-2 pr-2">
                                    <div id="title" class="post-title">
                                        <h2 class="title post-title-h2"><?=$loadout['title']?></h2>
                                    </div>
                                    <div class="post-upload-info">
                                        <span><i class="fa-solid fa-clock"></i> <?=strftime( "%d de %B de %Y" , $loadout['creationDate'])?></span>
                                        <span class="ml-2"><i class="fa-solid fa-circle i-font-size"></i> SudoKiss</span>
                                    </div>
                                    <div class="posts-description is-block">
                                        <p class="is-text posts-description has-text-justified">
                                            <?=substr($loadout['description'][0]['partZero'], 0, 100);?>...
                                        </p>
                                    </div>
                                </a>
                                <div class="read-more">
                                    <a href="/clases/<?=$loadout['gameUri']?>/<?=$loadout['loadout_id']?>/<?=$loadout['loadoutUri']?>" class="pb-2 pl-2 pr-2">Leer más <<<</a>
                                </div>
                            </article>
                        <?php endforeach; ?>
                    </div>
                </div>

                <!---- TUTORIALS --->
                <div id="tutorials" class="tutorials is-inline-block p-3" >
                    <h2 class="title">Tutoriales</h2>
                    <div class="column is-relative is-flex custom-column is-flex-direction-column">
                        <a class="custom-column__img-link" href="/tutoriales/<?=$lastTutorial['lowerCatName']?>/<?=$lastTutorial['tutorial_id']?>/<?=$lastTutorial['uriTitle']?>">
                            <figure class="image is-100-height">
                                <img class="object-fit" src="/uploads/images/tutorial/<?=$lastTutorial['categoryName']?>/<?=$lastTutorial['titleImage']?>">
                            </figure>
                        </a>
                        <div class="bottom-banner p-3 is-flex justify-self-start is-flex-direction-column is-align-items-self-start">
                            <a href="/tutoriales/<?=$lastTutorial['lowerCatName']?>" id="post-category" class="category custom-category ml-2 mt-1" ><?=$lastTutorial['categoryName']?></a>
                            <a href="/tutoriales/<?=$lastTutorial['lowerCatName']?>/<?=$lastTutorial['tutorial_id']?>/<?=$lastTutorial['uriTitle']?>">
                                <div id="title" class="post-title custom-title mt-2 ml-2 mr-2">
                                    <h2 class="title custom-title-h2"><?=$lastTutorial['title']?></h2>
                                </div>
                                <div class="post-upload-info is-flex is-justify-content-start ml-2 mr-2 mt-2 is-flex-direction-column-widescreen">
                                    <span class="has-text-white custom-span"><i class="fa-solid fa-clock"></i> <?=strftime( "%d de %B de %Y" , $lastTutorial['creationDate'])?></span>
                                    <span class="ml-2 has-text-white custom-span"><i class="fa-solid fa-circle i-font-size"></i> SudoKiss</span>
                                </div>
                            </a>
                        </div>
                    </div>
                    <ul class="home-list">
                        <?php foreach ( $someTutorials as $tutorial ): ?>
                            <li><a href="/tutoriales/<?=$tutorial['lowerCatName']?>/<?=$tutorial['tutorial_id']?>/<?=$tutorial['uriTitle']?>"><?=$tutorial['title']?></a></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <div class="is-clearfix"></div>
            </div>
        </div>


