<?php
?>
<section class="section is-100-vheight">
    <div class="container has-text-centered">
        <div class="is-flex is-justify-content-center is-flex-direction-column">
            <h1 class="title is-1 ">Sitio en Mantención <i class="fa-solid fa-gear"></i></h1>
            <p class="subtitle is-3 mt-2">Lamentamos los inconvenientes, vuelve más tarde</p>
        </div>
    </div>
</section>
