
        </section>
        <footer class="footer p-1 has-background-grey has-text-centered is-flex is-flex-direction-column">
            <span class="has-text-white is-size-5 mt-3">All Rights &copy; <?=date('Y')?></span>
            <figure class="image is-inline-block footer-logo-width m-auto">
                <img src="/uploads/logo.png">
            </figure>
            <div class="mb-3">
                <span class="has-text-white">Sitio Web dedicado a Call of Duty</span>
            </div>
        </footer>
    </body>
</html>