<?php
/* @var string $viewTitle */
?>

<!DOCTYPE html>
<html class="has-background-grey-lighter" lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><?=!is_null($viewTitle) ? $viewTitle : 'Administrador'?></title>
        <link rel="shortcut icon" type="image/png" href="/uploads/favicon.png">
        <link rel="stylesheet" type="text/css" href="/css/mystyles"><link>
        <script src="https://kit.fontawesome.com/81bf225702.js" crossorigin="anonymous"></script>
    </head>
<body>
